name: tcp_tunnel
description: A simple TCP tunnels library using pure Dart. Comes with a CLI for easy usage in any platform.
version: 1.0.0
repository: https://github.com/gmpassos/tcp_tunnel

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  dependency_validator: ^3.2.2
  test: ^1.16.0
