name: tcp_tunnel
description: A minimalistic TCP tunnel library, entirely written in Dart, and equipped with a user-friendly Command Line Interface (CLI) for seamless usage across diverse platforms.
version: 1.0.0
repository: https://github.com/gmpassos/tcp_tunnel

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  dependency_validator: ^3.2.2
  test: ^1.24.3
